### ISSUE TITLE
Command tcpconnect throws "Host is unreachable" error message - JSP agent

### ISSUE THREAD

**Issue by Kudaes** [kraken-ng/Kraken#1]
I'm trying to perform a small port scan to internal network assets using the tcpconnect command of the standard jsp agent. However, I keep receiving the error message on the title  when I try to scan any port on a remote host, despite that I actually can reach those ports using other tools like NetCat.

I dont receive this error message when I scan open ports in any of the network interfaces of the host where the agent is running. In those cases, the module is working properly, so it seems that it fails when you scan ports on remote hosts. 

I have tried using the delay flag up to 20 seconds, but it did not fix the issue. Also, I've tried increasing the value of the constant TIMEOUT in the module itself, but it hasn't work either.

**Comment by secu77** [comment]
Okay, I'll see if I can recreate it in one of my environments and see what mitigation to apply. Thanks for reporting it (;

**Comment by secu77** [comment]
I move this issue to the modules repository: https://github.com/kraken-ng/modules/issues/4
